on:
  workflow_dispatch:
    inputs:
      ACTIVE_API_URL:
        description: 'The URL of the scanner settings'
        default: 'https://10.10.10.184/active'
        required: false
        type: string
      ACTIVE_SEVERITY_THRESHOLD:
        description: build disturb on error level supported values [high , medium, low, info, none]
        default: none
        required: false
        type: choice
        options:
          - high
          - medium
          - low
          - info
          - none
      ACTIVE_CONFIG_FILE_PATH:
        description: The config file path.
        default: 'active-config.json'
        required: false
        type: string
      ACTIVE_TEST_GROUP_ID:
        description: test group id.
        default: '62f5921c-d200-4f6f-a104-29674ad30a94'
        required: false
        type: string
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: jfrog.cicd.nonamesec.com/noname-docker-release
          username: kbbank@nonamesecurity.com
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

      - name: security test
        run: |
          docker run --pull always -e ACTIVE_CONFIG_FILE_PATH=${{ github.event.inputs.ACTIVE_CONFIG_FILE_PATH }} -v $(pwd)/noname:/noname \

          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${{github.event.inputs.ACTIVE_API_URL}}/backend/version) scan --api-url=${{ github.event.inputs.ACTIVE_API_URL }} \
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} --severity-threshold=${{ github.event.inputs.ACTIVE_SEVERITY_THRESHOLD }} --test-group-id=${{ github.event.inputs.ACTIVE_TEST_GROUP }} --branch-name=${{ github.head_ref || github.ref_name }} --network host

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Hello world
