on:
  workflow_dispatch:
    inputs:
      ACTIVE_API_URL:
        description: 'The URL of the scanner settings'
        default: 'https://10.10.10.184/active'
        required: false
        type: string
      ACTIVE_SEVERITY_THRESHOLD:
        description: build disturb on error level supported values [high , medium, low, info, none]
        default: none
        required: false
        type: choice
        options:
          - high
          - medium
          - low
          - info
          - none
     	ACTIVE_CONFIG_FILE_PATH:
        description: The config file path.
        default: 'active_config.json'
        required: false
        type: string
	ACTIVE_TEST_GROUP_ID:
        description: test group id.
        default: '62f5921c-d200-4f6f-a104-29674ad30a94'
        required: false
        type: string
